version: '3.8'

services:  
  mysqldb:
    image: mysql:8.0
    restart: always
    command:  --default-authentication-plugin=mysql_native_password 
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - --skip-name-resolve
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    expose:
      - $DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  server:
    build: .
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_DOCKER_PORT
      - WAIT_HOSTS=mysqldb:3306
    stdin_open: true
    tty: true

volumes: 
  db: