version: '3.8'

services:  
  mysqldb:
    image: mysql:8.0
    restart: always
    command:  --default-authentication-plugin=mysql_native_password 
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    expose:
      - $DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  server:
    depends_on: 
      - mysqldb
    build: 
      context: .
      dockerfile: ./test/Test.Dockerfile
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_DOCKER_PORT
      - WAIT_HOSTS=mysqldb:3306
    stdin_open: true
    tty: true

volumes: 
  db: